version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-qiita-stocker-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1e8zji90bpbb0"
s3_prefix = "dev-qiita-stocker-lambda"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
