AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5

Resources:
  HaltRdsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: halt-rds
      Runtime: go1.x
      Tracing: Active
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds:StopDBCluster
              Resource: '*'
      Events:
        StartScan:
          Type: Schedule
          Properties:
            Schedule: cron(0 18 ? * * *)

  HaltRdsFuncLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HaltRdsFunction}
      RetentionInDays: 7
